import { Staff, AIInsight, WeeklyAvailability, Role } from "@/types";

// Demo staff data
export const demoStaff: Staff[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@restaurant.com",
    role: "BARTENDER" as Role,
    skills: ["Cocktail Making", "Wine Knowledge", "Customer Service"],
    wageRate: 18.5,
    maxHours: 35,
    availability: {
      monday: {
        available: true,
        startTime: "17:00",
        endTime: "23:00",
        preferredShifts: ["evening"],
      },
      tuesday: {
        available: true,
        startTime: "17:00",
        endTime: "23:00",
        preferredShifts: ["evening"],
      },
      wednesday: {
        available: true,
        startTime: "17:00",
        endTime: "23:00",
        preferredShifts: ["evening"],
      },
      thursday: {
        available: true,
        startTime: "17:00",
        endTime: "23:00",
        preferredShifts: ["evening"],
      },
      friday: {
        available: true,
        startTime: "16:00",
        endTime: "24:00",
        preferredShifts: ["evening"],
      },
      saturday: {
        available: true,
        startTime: "16:00",
        endTime: "24:00",
        preferredShifts: ["evening"],
      },
      sunday: { available: false },
    } as WeeklyAvailability,
    isActive: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-09-20"),
  },
  {
    id: "2",
    name: "Mike Rodriguez",
    email: "mike.rodriguez@restaurant.com",
    role: "WAITER" as Role,
    skills: ["Table Service", "POS Systems", "Food Knowledge", "Multilingual"],
    wageRate: 15.0,
    maxHours: 40,
    availability: {
      monday: {
        available: true,
        startTime: "11:00",
        endTime: "19:00",
        preferredShifts: ["afternoon"],
      },
      tuesday: {
        available: true,
        startTime: "11:00",
        endTime: "19:00",
        preferredShifts: ["afternoon"],
      },
      wednesday: {
        available: true,
        startTime: "11:00",
        endTime: "19:00",
        preferredShifts: ["afternoon"],
      },
      thursday: {
        available: true,
        startTime: "11:00",
        endTime: "19:00",
        preferredShifts: ["afternoon"],
      },
      friday: {
        available: true,
        startTime: "11:00",
        endTime: "22:00",
        preferredShifts: ["afternoon", "evening"],
      },
      saturday: {
        available: true,
        startTime: "10:00",
        endTime: "22:00",
        preferredShifts: ["afternoon", "evening"],
      },
      sunday: {
        available: true,
        startTime: "10:00",
        endTime: "18:00",
        preferredShifts: ["morning", "afternoon"],
      },
    } as WeeklyAvailability,
    isActive: true,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-09-20"),
  },
  {
    id: "3",
    name: "Emily Chen",
    email: "emily.chen@restaurant.com",
    role: "COOK" as Role,
    skills: ["Grill Master", "Prep Work", "Food Safety", "Italian Cuisine"],
    wageRate: 20.0,
    maxHours: 38,
    availability: {
      monday: {
        available: true,
        startTime: "14:00",
        endTime: "22:00",
        preferredShifts: ["evening"],
      },
      tuesday: {
        available: true,
        startTime: "14:00",
        endTime: "22:00",
        preferredShifts: ["evening"],
      },
      wednesday: {
        available: true,
        startTime: "14:00",
        endTime: "22:00",
        preferredShifts: ["evening"],
      },
      thursday: {
        available: true,
        startTime: "14:00",
        endTime: "22:00",
        preferredShifts: ["evening"],
      },
      friday: {
        available: true,
        startTime: "12:00",
        endTime: "23:00",
        preferredShifts: ["afternoon", "evening"],
      },
      saturday: {
        available: true,
        startTime: "12:00",
        endTime: "23:00",
        preferredShifts: ["afternoon", "evening"],
      },
      sunday: { available: false },
    } as WeeklyAvailability,
    isActive: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-09-20"),
  },
  {
    id: "4",
    name: "David Thompson",
    email: "david.thompson@restaurant.com",
    role: "WAITER" as Role,
    skills: ["Table Service", "Wine Service", "Customer Relations"],
    wageRate: 16.0,
    maxHours: 32,
    availability: {
      monday: { available: false },
      tuesday: { available: false },
      wednesday: {
        available: true,
        startTime: "17:00",
        endTime: "23:00",
        preferredShifts: ["evening"],
      },
      thursday: {
        available: true,
        startTime: "17:00",
        endTime: "23:00",
        preferredShifts: ["evening"],
      },
      friday: {
        available: true,
        startTime: "17:00",
        endTime: "24:00",
        preferredShifts: ["evening"],
      },
      saturday: {
        available: true,
        startTime: "17:00",
        endTime: "24:00",
        preferredShifts: ["evening"],
      },
      sunday: {
        available: true,
        startTime: "16:00",
        endTime: "22:00",
        preferredShifts: ["evening"],
      },
    } as WeeklyAvailability,
    isActive: true,
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-09-20"),
  },
  {
    id: "5",
    name: "Lisa Anderson",
    email: "lisa.anderson@restaurant.com",
    role: "HOST" as Role,
    skills: ["Customer Service", "Reservation Systems", "Phone Etiquette"],
    wageRate: 14.0,
    maxHours: 25,
    availability: {
      monday: {
        available: true,
        startTime: "16:00",
        endTime: "21:00",
        preferredShifts: ["evening"],
      },
      tuesday: {
        available: true,
        startTime: "16:00",
        endTime: "21:00",
        preferredShifts: ["evening"],
      },
      wednesday: {
        available: true,
        startTime: "16:00",
        endTime: "21:00",
        preferredShifts: ["evening"],
      },
      thursday: {
        available: true,
        startTime: "16:00",
        endTime: "21:00",
        preferredShifts: ["evening"],
      },
      friday: {
        available: true,
        startTime: "15:00",
        endTime: "23:00",
        preferredShifts: ["afternoon", "evening"],
      },
      saturday: {
        available: true,
        startTime: "15:00",
        endTime: "23:00",
        preferredShifts: ["afternoon", "evening"],
      },
      sunday: { available: false },
    } as WeeklyAvailability,
    isActive: true,
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-09-20"),
  },
  {
    id: "6",
    name: "James Wilson",
    email: "james.wilson@restaurant.com",
    role: "BARTENDER" as Role,
    skills: [
      "Craft Cocktails",
      "Beer Knowledge",
      "Customer Service",
      "Inventory",
    ],
    wageRate: 17.5,
    maxHours: 30,
    availability: {
      monday: { available: false },
      tuesday: { available: false },
      wednesday: { available: false },
      thursday: {
        available: true,
        startTime: "19:00",
        endTime: "24:00",
        preferredShifts: ["evening"],
      },
      friday: {
        available: true,
        startTime: "18:00",
        endTime: "02:00",
        preferredShifts: ["evening"],
      },
      saturday: {
        available: true,
        startTime: "18:00",
        endTime: "02:00",
        preferredShifts: ["evening"],
      },
      sunday: {
        available: true,
        startTime: "17:00",
        endTime: "23:00",
        preferredShifts: ["evening"],
      },
    } as WeeklyAvailability,
    isActive: true,
    createdAt: new Date("2024-03-12"),
    updatedAt: new Date("2024-09-20"),
  },
  {
    id: "7",
    name: "Maria Santos",
    email: "maria.santos@restaurant.com",
    role: "WAITER" as Role,
    skills: ["Table Service", "Cash Handling", "Spanish Speaker", "Upselling"],
    wageRate: 15.5,
    maxHours: 35,
    availability: {
      monday: {
        available: true,
        startTime: "09:00",
        endTime: "17:00",
        preferredShifts: ["morning", "afternoon"],
      },
      tuesday: {
        available: true,
        startTime: "09:00",
        endTime: "17:00",
        preferredShifts: ["morning", "afternoon"],
      },
      wednesday: {
        available: true,
        startTime: "09:00",
        endTime: "17:00",
        preferredShifts: ["morning", "afternoon"],
      },
      thursday: {
        available: true,
        startTime: "09:00",
        endTime: "17:00",
        preferredShifts: ["morning", "afternoon"],
      },
      friday: {
        available: true,
        startTime: "09:00",
        endTime: "17:00",
        preferredShifts: ["morning", "afternoon"],
      },
      saturday: { available: false },
      sunday: { available: false },
    } as WeeklyAvailability,
    isActive: true,
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-09-20"),
  },
  {
    id: "8",
    name: "Robert Kim",
    email: "robert.kim@restaurant.com",
    role: "COOK" as Role,
    skills: [
      "Asian Cuisine",
      "Wok Cooking",
      "Prep Work",
      "Kitchen Organization",
    ],
    wageRate: 19.0,
    maxHours: 40,
    availability: {
      monday: {
        available: true,
        startTime: "10:00",
        endTime: "18:00",
        preferredShifts: ["morning", "afternoon"],
      },
      tuesday: {
        available: true,
        startTime: "10:00",
        endTime: "18:00",
        preferredShifts: ["morning", "afternoon"],
      },
      wednesday: {
        available: true,
        startTime: "10:00",
        endTime: "18:00",
        preferredShifts: ["morning", "afternoon"],
      },
      thursday: {
        available: true,
        startTime: "10:00",
        endTime: "18:00",
        preferredShifts: ["morning", "afternoon"],
      },
      friday: {
        available: true,
        startTime: "10:00",
        endTime: "18:00",
        preferredShifts: ["morning", "afternoon"],
      },
      saturday: {
        available: true,
        startTime: "09:00",
        endTime: "17:00",
        preferredShifts: ["morning", "afternoon"],
      },
      sunday: { available: false },
    } as WeeklyAvailability,
    isActive: true,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-09-20"),
  },
];

// Demo AI insights
export const demoInsights: AIInsight[] = [
  {
    id: "1",
    type: "warning",
    title: "Bartenders Overloaded This Weekend",
    description:
      "Your bartenders are scheduled for 45+ hours this week. Consider redistributing shifts or hiring temporary help.",
    actionable: true,
    action: {
      label: "Adjust Schedule",
      type: "navigate",
      target: "/staff",
    },
    priority: "high",
    createdAt: new Date(),
  },
  {
    id: "2",
    type: "suggestion",
    title: "Optimal Staffing Opportunity",
    description:
      "Friday evening shows 20% higher revenue potential with one additional waiter. Current coverage may be insufficient.",
    actionable: true,
    action: {
      label: "Review Schedule",
      type: "create",
      target: "schedule",
    },
    priority: "medium",
    createdAt: new Date(),
  },
  {
    id: "3",
    type: "info",
    title: "Staff Performance Above Average",
    description:
      "Your team is performing 15% above industry standards this month. Sarah (Bartender) leads with 9.2/10 rating.",
    actionable: false,
    priority: "low",
    createdAt: new Date(),
  },
  {
    id: "4",
    type: "warning",
    title: "Missing Sunday Morning Coverage",
    description:
      "No waiters scheduled for Sunday 10 AM - 2 PM shift. This could impact brunch service.",
    actionable: true,
    action: {
      label: "Find Coverage",
      type: "update",
      target: "schedule",
    },
    priority: "high",
    createdAt: new Date(),
  },
  {
    id: "5",
    type: "success",
    title: "Cost Optimization Success",
    description:
      "Last week's schedule adjustments reduced overtime costs by $340 while maintaining service quality.",
    actionable: false,
    priority: "low",
    createdAt: new Date(),
  },
  {
    id: "6",
    type: "suggestion",
    title: "Cross-Training Recommendation",
    description:
      "Training Maria (Waiter) in hosting duties could improve scheduling flexibility by 30%.",
    actionable: true,
    action: {
      label: "Plan Training",
      type: "navigate",
      target: "/staff",
    },
    priority: "medium",
    createdAt: new Date(),
  },
];

// Function to initialize demo data
export function initializeDemoData() {
  return {
    staff: demoStaff,
    insights: demoInsights,
    shifts: [], // Will be populated by scheduling system
    analytics: {
      totalStaff: demoStaff.length,
      activeStaff: demoStaff.filter((s) => s.isActive).length,
      totalShifts: 104,
      completedShifts: 98,
      totalWageCost: demoStaff.reduce((sum, s) => sum + s.wageRate * 30, 0),
      averageHoursPerStaff: 32.5,
      shiftFulfillmentRate: 94.2,
      roleDistribution: {
        WAITER: 3,
        BARTENDER: 2,
        COOK: 2,
        HOST: 1,
        CLEANER: 0,
        MANAGER: 0,
      },
      weeklyTrends: [
        { date: "2024-09-16", shifts: 18, cost: 2100, staffCount: 8 },
        { date: "2024-09-17", shifts: 16, cost: 1800, staffCount: 7 },
        { date: "2024-09-18", shifts: 20, cost: 2300, staffCount: 9 },
        { date: "2024-09-19", shifts: 22, cost: 2500, staffCount: 10 },
        { date: "2024-09-20", shifts: 24, cost: 2800, staffCount: 11 },
        { date: "2024-09-21", shifts: 28, cost: 3200, staffCount: 12 },
        { date: "2024-09-22", shifts: 22, cost: 2600, staffCount: 10 },
      ],
    },
  };
}
